name: Frontend workflow

on:
  push:
    paths:
      - 'web/**'
  pull_request:
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test JS frontend
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install requirements
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2
        with:
          flags: frontend
